"""add fields  to User

Revision ID: 3226404a08fe
Revises: 512dfcb2d75d
Create Date: 2025-05-11 18:49:13.656401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3226404a08fe'
down_revision: Union[str, None] = '512dfcb2d75d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(), nullable=True))
    op.add_column('user', sa.Column('disabled', sa.Boolean(), nullable=False, server_default=sa.text("False") ))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'disabled')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
