from typing import Protocol, Optional
from app.domain.models.User import User, UserwithoutPassword

class AuthServiceProtocol(Protocol):
    def authenticate(self, username: str, password: str) -> Optional[UserwithoutPassword]: ...
    def get_user_from_token(self, token: str) -> User: ...
    def ensure_user_is_active(self, user: User) -> User: ...
