from typing import Protocol
from app.domain.models.ReportingSummary import ReportingSummary, ReportingSummaryFilter, TotalsByCertification

from typing import List

class ReportingSummaryProtocol(Protocol):
    def create_summary(self, reporting : ReportingSummary) -> ReportingSummary | None : ...
    
    def list_all_summaries(self) -> list[ReportingSummary] | None : ...

    def get_grouped_summary(self) -> list[ReportingSummary] | None : ...
    
    def get_filtered_summaries(self, filters: ReportingSummaryFilter) -> list[ReportingSummary]:
        ...
    def get_totals_by_certification(self) -> TotalsByCertification | None : ...

    def get_last_invoice_name(self) -> str | None : ...