from typing import Protocol, Optional
from datetime import timedelta

class SecurityServiceProtocol(Protocol):
    def verify_password(self, plain_password: str, hashed_password: str) -> bool: ...
    def hash_password(self, password: str) -> str: ...
    def create_access_token(self, data: dict, expires_delta: Optional[timedelta] = None) -> str: ...
    def decode_token(self, token: str) -> dict: ...
