/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as StatisticImport } from './routes/statistic'
import { Route as InvoicesImport } from './routes/invoices'
import { Route as BilanImport } from './routes/bilan'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const StatisticRoute = StatisticImport.update({
  id: '/statistic',
  path: '/statistic',
  getParentRoute: () => rootRoute,
} as any)

const InvoicesRoute = InvoicesImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRoute,
} as any)

const BilanRoute = BilanImport.update({
  id: '/bilan',
  path: '/bilan',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/bilan': {
      id: '/bilan'
      path: '/bilan'
      fullPath: '/bilan'
      preLoaderRoute: typeof BilanImport
      parentRoute: typeof rootRoute
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesImport
      parentRoute: typeof rootRoute
    }
    '/statistic': {
      id: '/statistic'
      path: '/statistic'
      fullPath: '/statistic'
      preLoaderRoute: typeof StatisticImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bilan': typeof BilanRoute
  '/invoices': typeof InvoicesRoute
  '/statistic': typeof StatisticRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bilan': typeof BilanRoute
  '/invoices': typeof InvoicesRoute
  '/statistic': typeof StatisticRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/bilan': typeof BilanRoute
  '/invoices': typeof InvoicesRoute
  '/statistic': typeof StatisticRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bilan' | '/invoices' | '/statistic'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bilan' | '/invoices' | '/statistic'
  id: '__root__' | '/' | '/bilan' | '/invoices' | '/statistic'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BilanRoute: typeof BilanRoute
  InvoicesRoute: typeof InvoicesRoute
  StatisticRoute: typeof StatisticRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BilanRoute: BilanRoute,
  InvoicesRoute: InvoicesRoute,
  StatisticRoute: StatisticRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/bilan",
        "/invoices",
        "/statistic"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/bilan": {
      "filePath": "bilan.tsx"
    },
    "/invoices": {
      "filePath": "invoices.tsx"
    },
    "/statistic": {
      "filePath": "statistic.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
