from typing import Protocol, Optional, Dict, Any
from datetime import timedelta


class AuthServiceProtocol(Protocol):
    def verify_password(self, plain_password: str, hashed_password: str) -> bool: ...
    def create_access_token(self, subject: str, expires_delta: Optional[timedelta] = None) -> str: ...
    def decode_token(self, token: str) -> Dict[str, Any]: ...