from typing import Protocol
from app.domain.models.User import User

class AuthServiceProtocol(Protocol):
    def authenticate(self, username: str, password: str) -> User | None : ...
    def get_user_from_token(self, token: str) -> User: ...
    def ensure_user_is_active(self, user: User) -> User: ...
